spring:
  application:
    name: FocusList (Lista de tarefas com sistema de cadastro de Usuário).
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/TodoList
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}